export default {
  initialize: 'initialize',
  hashchange: 'hashchange',
  pending: 'pending',
  channelSelect: 'channelSelect',
  channelSelected: 'channelSelected',
  channelReceive: 'channelReceive',
  channelAdd: 'channelAdd',
  settingReceive: 'settingReceive',
  settingUpdate: 'settingUpdate',
  itemSelect: 'itemSelect',
  itemSelectRelative: 'itemSelectRelative',
  viewStart: 'viewStart',
  viewEnd: 'viewEnd',
  refScreen: 'refScreen',
};
